import type { NextPage } from 'next';
import Head from 'next/head';

import Header from '../components/navigation/header';
import Footer from '../components/navigation/footer';

const Home: NextPage = () => {
  return (
    <div className="w-full min-h-screen flex flex-col">
      <Head>
        <title>NIFTY</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="flex-1 container mx-auto px-6 mb-20 md:px-0"></main>

      <Footer />
    </div>
  );
};

export default Home;
